apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gagent.fullname" . }}-config
  labels:
    {{- include "gagent.labels" . | nindent 4 }}
data:
  log-level: {{ .Values.config.logLevel | quote }}
  model-registry-enabled: {{ .Values.config.modelRegistryEnabled | quote }}
  tier-selection: {{ .Values.config.tierSelection | quote }}
